### ISSUE TITLE
Implement Delete Resource

### ISSUE THREAD

**Issue by samgomena** [deepmarket/PLUTO#50]
The application should allow a user to delete a resource that has been added via PLUTO. To do this, we'll need to send a `DELETE` request to the `/resources/<resource_id>` endpoint.

For a better overview of the resource endpoint functionality, you can refer to the [resource endpoint](https://github.com/shared-systems/api/wiki/API-Enpoints#resources-resources) wiki.

**Comment by lixphilosophy** [comment]
Problem need to be taken care when server is up. Consider to add api request on `on_remove_button_clicked` at `resources.py` to delete resource at backend.

**Comment by samgomena** [comment]
I'm not sure what you're saying here. Can you post a permalink to line number/function relating to the problem?

**Comment by lixphilosophy** [comment]
Well, 
[here it is.](https://github.com/shared-systems/PLUTO/blob/2ccc7495a1cb57522e9b79f7d95ffd7384377cfe/src/resources.py#L393)
What I want to say is the problem could be taken care of once server is up. So technically, we should wait until the ssh problem fix.

**Comment by samgomena** [comment]
The server is up! Also, it won't (shouldn't) go down due to any of the ssh stuff we're doing. So you should be able to get this working!

As an aside, these lines right under the permalink:
```python
        # check if table has selected row
        if not model.hasSelection():
            pass
        else:
            ...
```
can be shortened to this:
```python
        # check if table has selected row
        if model.hasSelection():
            ...
```
as the `pass` statement only serves as a noop if there's not a selection.

**Comment by lixphilosophy** [comment]
I try to launch the application today. Either login straightly or register new account. Neither of them works. Or, could you point me out how could I get into the main dashboard?

**Comment by samgomena** [comment]
Have you pulled the latest code from develop? If so, and it still doesn’t work, make sure the server’s FQDN in api.py is set to pacific.cs.pdx.edu!


________________________________

**Comment by lixphilosophy** [comment]
fixed
