### ISSUE TITLE
User verification while adding resources through PLUTO

### ISSUE THREAD

**Issue by susham** [deepmarket/PLUTO#52]
Current implementation doesn't consider verifying the resources to whom the worker machine belongs to, as we are taking the ipaddress as the input from the user. It is easy for a user to input the ipaddress of any machine. 

1. How can we verify that a machine added by the user is his own?
2. Should we ask the user to(for Version1):
       a. Create a new user, specifically for the PLUTO?
       b. Ask for the user credentials to create the spark worker container?

**Comment by lixphilosophy** [comment]
I don't think so. @samgomena I think  Sam has been modified the way that we achieve ip address. The last version of PLUTO would typically use socket to open a tcp connection then get the socket’s own address.
A reference link for this method: https://www.geeksforgeeks.org/python-program-find-ip-address/
Now, we don't need or allow user to input ip address.
1. We don't need to know if he own the machine he added. We just need to know that the machine he added is the one he currently operated on. In my opinion, user should be able to add a machine that he can access. Also, we have no way to do a two-factor authentication to verify this.
2. a. initially, we required user to create their account.
2. b. I agree, it would be a good idea, but here's some questions:
    1. how do spark know the credentials?
    2. the schema of resources need to be modified.
    3. while different user use the the machine, would the credential be the same?

**Comment by susham** [comment]
@lixphilosophy @samgomena There are 2 ways of allowing the user to add resources

1. Add the user's machine on which he has installed the PLUTO.
2. Allow user to add another machine to which he has access to as the worker machine (Version 2)

As per my understanding, the current version of PLUTO does the first point above,  this issue is raised to avoid the issue of the user giving any random IP address that he knows of and successfully adding the worker machine under his account.

**Comment by lixphilosophy** [comment]
Yes, I think you are correct. PLUTO currently takes Version 1 approach to the problem.

Version 2 approach required to verify the ownership of the target machine. One solution would be in the target machine, we have a receiver or socket application, which listen to the verify signal. Then PLUTO would have a verification button, which emit verify signal.

**Comment by susham** [comment]
@lixphilosophy @samgomena  

Even in version 1, I do not have any idea about the permissions required to install PLUTO on a Linux machine.

Does the user need to be an administrator to install and add the resources? If so, then we can discuss how the add resource functionality will be for version 2.

If not, then we need to understand what are the assumptions we are going with for version 1.

**Comment by lixphilosophy** [comment]
@susham @samgomena 
There's currently no permission required when using PLUTO. Also, I think we cannot make any assumptions until we actually create docker for spark worker. I guess during the time we might need to run the application as administrator. The problem can be raised up again when we work on the integration.

**Comment by lixphilosophy** [comment]
Issue out of time.
