### ISSUE TITLE
read_stylesheet Attempts to Open Stylesheet Files Improperly

### ISSUE THREAD

**Issue by samgomena** [deepmarket/PLUTO#61]
The issue we were having with the application "freezing" on startup is due to the `read_stylesheet` function making an assumption about the path to the stylesheet it's trying to read.

Namely, this is because of the `load_path(...)` function returning False when the path it's given isn't found. `load_path` also does not properly search the file tree (it looks like it was improperly copied from it's source). `read_stylesheet` then attempts to `open(False)` which hangs (see demo code below).

Both of these functions should be fixed so that they appropriately determine a stylesheet's path and display an error/warning if it can't be found. Additionally, we should probably add some unit tests for them since these functions are important as well as simple in logic. This functionality should also not depend on location of a built executable, location of entry into the application, or the OS the application is being run on.

```python
Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> with open(False) as file: print(file.read())
... 
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyboardInterrupt
>>> 
```

**Comment by lixphilosophy** [comment]
I have done some research. To reach to goal that determine the stylesheet's (or some other media data) path, I found that the best solution would be improve our usage on `fbs`. From a long considered aspect, to fully using `fbs` can help a lot when we want to deploy the application.

`fbs` projects use the following directory structure (detail can be found [here](https://build-system.fman.io/manual/#directory-structure)):
```
   src/                                    - Root directory for your source files
        build/                             - Files for the build process
        main/                              - Implementation of your app
             icons/                        - Application's icon.
             python/                       - The folder places our python code
                   main.py                 - Application starting stript (as we do)
             (resources/)                  - The folder places all data files
```

We put all of our data files (stylesheet, img, etc.) into the resources folder. Then later on when we define our `AppContext` class, we will have a function call `get_resource`, which will look for the files in this folder. Here's a short example:

See now we have a file call `app.qss` in resource,
```
    resources/
    ┗ app.qss
```
Here's how we can define the class and find the file in the directory:
```python
class AppContext(ApplicationContext):
    def run(self):
        ...
        try:
            # go to resource folder looking for file 'app.qss'
            # if file exist, the absolute path to the file would be return
            file_path = self.get_resource('app.qss')

            # read file
            with open(file_path) as f:
                self. app_style = f.read()

       # If the given file does not exist, a FileNotFoundError is raised
       except FileNotFoundError:
            raise FileNotFoundError("file is not found!")
  
      # to use the resources that we just load in,
      # pass the context in and store a reference to our childwidget
       dont_garbage_collect_me = MainApp(self)
       return self.app.exec_()
```

Here's more reference and examples link:
[Packaging PyQt5 apps with fbs](https://www.learnpyqt.com/courses/packaging-and-distribution/packaging-pyqt5-apps-fbs/)
[fbs tutorial](https://github.com/mherrmann/fbs-tutorial#a-more-interesting-example)

I made a demo to test its performance, you can find in [here](https://github.com/lixphilosophy/fbs_demo/tree/master). It looks good when I run on my mac, but I don't if it is doing the same well on Windows/Linux. So, it would be a great help if any of you can pull my repo and run it on the other operating system.

By the way, I can see there's a lot advantage from `fbs`. When we want to lauch the application, without confused, we can just call `fbs run`. For deploy, we can called `fbs installer`. For testing, they have `fbs test`. The only one thing that I am worried about is I don't know if its testing module would have conflict with the one that we are using right now. And how difficult for us to transfer the project under such structure. Please fill me up!!

**Comment by logyball** [comment]
Do you think it would be worth it to:

1. Do a quick patch for this issue that basically just tests if load_path returns false and if so, displays an error message and quit gracefully
2. Create a new branch for restructuring the project more along the `fbs` intended file structure

If so I'll create two new branches - one for a quick fix that exits gracefully if load_path doesn't find what it needs (error message containing something like `tried to load {file} it wasn't found`, and another branch for the large-scale restructuring of the project into the fbs-prescribed structure

**Comment by logyball** [comment]
@lixphilosophy I ran your test repo and it works great on my windows machine so that looks promising for a file structure.  Running the fbs commands was very easy and allowed for quick builds.  I think that we should follow that direction

**Comment by samgomena** [comment]
I think we should move towards integrating fbs more rigidly. Which should also allow us to release application builds more consistently. Regardless, I'll close this issue and assume we'll begin working towards these goals.
