### ISSUE TITLE
PLUTO logout then login again, api get incorrect user information.

### ISSUE THREAD

**Issue by lixphilosophy** [deepmarket/PLUTO#69]
At the first login, using martin's account: `lixphilosophy@gmail.com`.
after login and get into app, having a api get request for the endpoint `/account`,
```python
   with Api("/account") as account:
       status, res = account.get()
       print(status, res)
```
output shows following:
```
200 {
'success': True, 
'error': None, 
'message': 'Successfully fetched account information.', 
'account': {
   'credits': 19.990000000000002, 
   '_id': '5d1e971d17048100108ff948', 
   'firstname': 'Martin', 
   'lastname': 'Li', 
   'email': 'lixphilosophy@gmail.com', 
   'password': '$2b$10$9f7.beQIO6VZNOLVskNY/u7bKYEKeF7/u2Bmp3R.Am/b3nTMVGAsm', 
   'status': 'Active', 
   'createdOn': '2019-07-05T00:17:33.349Z', 
   'updatedOn': '2019-07-05T00:17:33.349Z', 
   '__v': 0
}}
```
Logout the application (not close it) then login in again with Fenting's account: `test@gmail.com`.
As my understand, it should print out the account information for Fenting, since we login her account. However, Martin's information shows again (exactly like the one shows above)

**Comment by logyball** [comment]
Alright I've reproduced this issue locally with api on develop running on localhost and PLUTO running off of develop locally pointed to localhost (change Api() to have localhost as the host) with `pipenv run fbs run`.  You can see it in the UI by simply logging in and out with two different accounts - log in with the first, log out, log in with the second and you'll see the first users' information.

**Comment by logyball** [comment]
so after some initial investigation, it looks like PLUTO is doing something incorrectly.  The API looks to be functioning as designed.  When initially logging in, PLUTO sends api the correct username and password, the api compares them to entries in the DB, and if successfully found, returns them to PLUTO after finding the user_id attribute from mongo.  However, immediately after hitting the /login api endpoint, PLUTO queries `GET /api/v1/account`, with a cached user_id.  That User_id is used to find account information, and is not cleared upon logout.  So __I think__ the fix here will be to make sure that we are clearing that user_id when logging out.  I'm not entirely sure where it's stored but I'm guessing it has something to do with the `.credential_store` file that is written by PLUTO.  Thoughts?

**Comment by samgomena** [comment]
That's correct. In fact, after looking at some code on an old branch of mine I found what looks like an attempt to fix that issue (though it doesn't appear to work atm). I think a better fix would be to ensure we update `.credential_store` with the new token provided on successful login -- and then ensuring we remove it on successful logout. I'm also able to take over this issue, or help you out with it if need be!

**Comment by logyball** [comment]
fixed here: https://github.com/deepmarket/PLUTO/pull/70
